// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXNr3pGZngwamiS1i_axXxE5CMSWlaQM',
    appId: '1:888943199862:web:56a2b99cc963aebb634157',
    messagingSenderId: '888943199862',
    projectId: 'uber-app-4fa4b',
    authDomain: 'uber-app-4fa4b.firebaseapp.com',
    storageBucket: 'uber-app-4fa4b.firebasestorage.app',
    databaseURL: 'https://uber-app-4fa4b-default-rtdb.firebaseio.com',
    measurementId: 'G-3WJKP3LYQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXNr3pGZngwamiS1i_axXxE5CMSWlaQM',
    appId: '1:888943199862:android:8649863fdea405f46aff72', // Placeholder - user should verify this
    messagingSenderId: '888943199862',
    projectId: 'uber-app-4fa4b',
    storageBucket: 'uber-app-4fa4b.firebasestorage.app',
    databaseURL: 'https://uber-app-4fa4b-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRXNr3pGZngwamiS1i_axXxE5CMSWlaQM',
    appId: '1:888943199862:ios:195e3a2ce8ca741b6aff72', // Placeholder - user should verify this
    messagingSenderId: '888943199862',
    projectId: 'uber-app-4fa4b',
    storageBucket: 'uber-app-4fa4b.firebasestorage.app',
    databaseURL: 'https://uber-app-4fa4b-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRXNr3pGZngwamiS1i_axXxE5CMSWlaQM',
    appId: '1:888943199862:ios:195e3a2ce8ca741b6aff72', // Placeholder - user should verify this
    messagingSenderId: '888943199862',
    projectId: 'uber-app-4fa4b',
    storageBucket: 'uber-app-4fa4b.firebasestorage.app',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRXNr3pGZngwamiS1i_axXxE5CMSWlaQM',
    appId: '1:888943199862:web:1ba91af64452404c6aff72', // Placeholder - user should verify this
    messagingSenderId: '888943199862',
    projectId: 'uber-app-4fa4b',
    authDomain: 'uber-app-4fa4b.firebaseapp.com',
    storageBucket: 'uber-app-4fa4b.firebasestorage.app',
    databaseURL: 'https://uber-app-4fa4b-default-rtdb.firebaseio.com',
    measurementId: 'G-FWENR48S6F',
  );
}
