// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZTKL51pRF5nNkv09rAic0wVkIuF32dg',
    appId: '1:57411926903:web:b6e5a3651feac0ed6aff72',
    messagingSenderId: '57411926903',
    projectId: 'uber-app-5873f',
    authDomain: 'uber-app-5873f.firebaseapp.com',
    storageBucket: 'uber-app-5873f.firebasestorage.app',
    measurementId: 'G-3WJKP3LYQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiowN09V7arV_cqAX4yvth4xHsd1nJgaU',
    appId: '1:57411926903:android:8649863fdea405f46aff72',
    messagingSenderId: '57411926903',
    projectId: 'uber-app-5873f',
    storageBucket: 'uber-app-5873f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDjdWp-yinQFyZMKTGzqhcL6kHjXN83AU',
    appId: '1:57411926903:ios:195e3a2ce8ca741b6aff72',
    messagingSenderId: '57411926903',
    projectId: 'uber-app-5873f',
    storageBucket: 'uber-app-5873f.firebasestorage.app',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDjdWp-yinQFyZMKTGzqhcL6kHjXN83AU',
    appId: '1:57411926903:ios:195e3a2ce8ca741b6aff72',
    messagingSenderId: '57411926903',
    projectId: 'uber-app-5873f',
    storageBucket: 'uber-app-5873f.firebasestorage.app',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkZTKL51pRF5nNkv09rAic0wVkIuF32dg',
    appId: '1:57411926903:web:1ba91af64452404c6aff72',
    messagingSenderId: '57411926903',
    projectId: 'uber-app-5873f',
    authDomain: 'uber-app-5873f.firebaseapp.com',
    storageBucket: 'uber-app-5873f.firebasestorage.app',
    measurementId: 'G-FWENR48S6F',
  );
}
